<?php
/**
 * CartRuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaemo API
 *
 * Public api for Kaemo back office
 *
 * OpenAPI spec version: 1.0.52
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CartRuleTest Class Doc Comment
 *
 * @category    Class */
// * @description CartRule
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CartRuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CartRule"
     */
    public function testCartRule()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "id_customer"
     */
    public function testPropertyIdCustomer()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {

    }

    /**
     * Test attribute "partial_use"
     */
    public function testPropertyPartialUse()
    {

    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {

    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {

    }

    /**
     * Test attribute "date_add"
     */
    public function testPropertyDateAdd()
    {

    }

    /**
     * Test attribute "date_upd"
     */
    public function testPropertyDateUpd()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "date_from"
     */
    public function testPropertyDateFrom()
    {

    }

    /**
     * Test attribute "date_to"
     */
    public function testPropertyDateTo()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "quantity_per_user"
     */
    public function testPropertyQuantityPerUser()
    {

    }

    /**
     * Test attribute "minimum_amount"
     */
    public function testPropertyMinimumAmount()
    {

    }

    /**
     * Test attribute "minimum_amount_tax"
     */
    public function testPropertyMinimumAmountTax()
    {

    }

    /**
     * Test attribute "minimum_amount_currency"
     */
    public function testPropertyMinimumAmountCurrency()
    {

    }

    /**
     * Test attribute "every_recurring_payments"
     */
    public function testPropertyEveryRecurringPayments()
    {

    }

    /**
     * Test attribute "reduction_percent"
     */
    public function testPropertyReductionPercent()
    {

    }

    /**
     * Test attribute "reduction_amount"
     */
    public function testPropertyReductionAmount()
    {

    }

    /**
     * Test attribute "restriction_groups"
     */
    public function testPropertyRestrictionGroups()
    {

    }

}
