<?php
/**
 * FeaturesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaemo API
 *
 * Public api for Kaemo back office
 *
 * OpenAPI spec version: 1.0.40
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * FeaturesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FeaturesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for attachFeaturesToProduct
     *
     * .
     *
     */
    public function testAttachFeaturesToProduct()
    {

    }

    /**
     * Test case for attachFeaturesToVideo
     *
     * .
     *
     */
    public function testAttachFeaturesToVideo()
    {

    }

    /**
     * Test case for detachFeatureToProduct
     *
     * .
     *
     */
    public function testDetachFeatureToProduct()
    {

    }

    /**
     * Test case for getCategoryFeatures
     *
     * .
     *
     */
    public function testGetCategoryFeatures()
    {

    }

    /**
     * Test case for getFeatureValues
     *
     * .
     *
     */
    public function testGetFeatureValues()
    {

    }

    /**
     * Test case for getFeatures
     *
     * .
     *
     */
    public function testGetFeatures()
    {

    }

    /**
     * Test case for getProductFeatures
     *
     * .
     *
     */
    public function testGetProductFeatures()
    {

    }

    /**
     * Test case for getVideoFeatures
     *
     * .
     *
     */
    public function testGetVideoFeatures()
    {

    }

}
