<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaemo API
 *
 * Public api for Kaemo back office
 *
 * OpenAPI spec version: 1.0.51
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for attachFeaturesToProduct
     *
     * .
     *
     */
    public function testAttachFeaturesToProduct()
    {

    }

    /**
     * Test case for attachProductToCategory
     *
     * .
     *
     */
    public function testAttachProductToCategory()
    {

    }

    /**
     * Test case for attachVideoToProduct
     *
     * .
     *
     */
    public function testAttachVideoToProduct()
    {

    }

    /**
     * Test case for createProduct
     *
     * .
     *
     */
    public function testCreateProduct()
    {

    }

    /**
     * Test case for deleteProduct
     *
     * .
     *
     */
    public function testDeleteProduct()
    {

    }

    /**
     * Test case for detachFeatureToProduct
     *
     * .
     *
     */
    public function testDetachFeatureToProduct()
    {

    }

    /**
     * Test case for detachProductFromCategory
     *
     * .
     *
     */
    public function testDetachProductFromCategory()
    {

    }

    /**
     * Test case for getCategoryProducts
     *
     * .
     *
     */
    public function testGetCategoryProducts()
    {

    }

    /**
     * Test case for getCustomerHasAccessToProduct
     *
     * .
     *
     */
    public function testGetCustomerHasAccessToProduct()
    {

    }

    /**
     * Test case for getProduct
     *
     * .
     *
     */
    public function testGetProduct()
    {

    }

    /**
     * Test case for getProductActors
     *
     * .
     *
     */
    public function testGetProductActors()
    {

    }

    /**
     * Test case for getProductAttributes
     *
     * .
     *
     */
    public function testGetProductAttributes()
    {

    }

    /**
     * Test case for getProductAvailability
     *
     * .
     *
     */
    public function testGetProductAvailability()
    {

    }

    /**
     * Test case for getProductCategories
     *
     * .
     *
     */
    public function testGetProductCategories()
    {

    }

    /**
     * Test case for getProductCoverImage
     *
     * .
     *
     */
    public function testGetProductCoverImage()
    {

    }

    /**
     * Test case for getProductDirectors
     *
     * .
     *
     */
    public function testGetProductDirectors()
    {

    }

    /**
     * Test case for getProductExtracts
     *
     * .
     *
     */
    public function testGetProductExtracts()
    {

    }

    /**
     * Test case for getProductFeatures
     *
     * .
     *
     */
    public function testGetProductFeatures()
    {

    }

    /**
     * Test case for getProductGeolocations
     *
     * .
     *
     */
    public function testGetProductGeolocations()
    {

    }

    /**
     * Test case for getProductGeolocationsByIp
     *
     * .
     *
     */
    public function testGetProductGeolocationsByIp()
    {

    }

    /**
     * Test case for getProductImages
     *
     * .
     *
     */
    public function testGetProductImages()
    {

    }

    /**
     * Test case for getProducts
     *
     * .
     *
     */
    public function testGetProducts()
    {

    }

    /**
     * Test case for getProductsFromProduct
     *
     * .
     *
     */
    public function testGetProductsFromProduct()
    {

    }

    /**
     * Test case for getVideosFromProduct
     *
     * .
     *
     */
    public function testGetVideosFromProduct()
    {

    }

    /**
     * Test case for searchProducts
     *
     * .
     *
     */
    public function testSearchProducts()
    {

    }

    /**
     * Test case for setProductGeolocation
     *
     * .
     *
     */
    public function testSetProductGeolocation()
    {

    }

    /**
     * Test case for updateProduct
     *
     * .
     *
     */
    public function testUpdateProduct()
    {

    }

}
